version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: comments_app
      MYSQL_USER: comments_app
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      bash -c "exec mysqld --init-file=/docker-entrypoint-initdb.d/init.sql"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_NAME=comments_app
      - DB_USER=comments_app
      - DB_PASSWORD=123456
      - DB_LOGGING=false
      - CORS_ORIGIN=http://localhost:5173
      - SESSION_SECRET=session-secret
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
